<?php

namespace Database\Seeders;

use App\Models\ParentModel;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ParentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parents = [
            [
                'first_name' => 'Mahesh',
                'middle_name' => 'Chandra',
                'last_name' => 'Wijesiri',
                'date_of_birth' => '1980-03-15',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Software Engineer',
                'workplace' => 'Tech Solutions Lanka',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '123 Galle Road',
                'address_line2' => 'Apartment 4B',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0101',
                'mobile_phone' => '+94-77-555-0102',
                'work_phone' => '+94-11-555-0103',
                'email' => 'mahesh.wijesiri@email.com',
            ],
            [
                'first_name' => 'Dilmi',
                'middle_name' => 'Sachini',
                'last_name' => 'Samaranayaka',
                'date_of_birth' => '1982-07-22',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Teacher',
                'workplace' => 'Colombo International School',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '456 Duplication Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00400',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0201',
                'mobile_phone' => '+94-77-555-0202',
                'email' => 'dilmi.samaranayaka@email.com',
            ],
            [
                'first_name' => 'Susiru',
                'middle_name' => 'Lakshitha',
                'last_name' => 'Perera',
                'date_of_birth' => '1978-11-08',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Doctor',
                'workplace' => 'National Hospital Colombo',
                'relationship_type' => 'Father',
                'is_emergency_contact' => false,
                'address_line1' => '789 Flower Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0301',
                'mobile_phone' => '+94-77-555-0302',
                'work_phone' => '+94-11-555-0303',
                'email' => 'susiru.perera@email.com',
            ],
            [
                'first_name' => 'Oushadee',
                'middle_name' => 'Madhushika',
                'last_name' => 'Fernando',
                'date_of_birth' => '1983-05-14',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Nurse',
                'workplace' => 'Asiri Hospital',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '321 Baseline Road',
                'address_line2' => 'Unit 12',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00900',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0401',
                'mobile_phone' => '+94-77-555-0402',
                'email' => 'oushadee.fernando@email.com',
            ],
            [
                'first_name' => 'Chamara',
                'middle_name' => 'Prasanna',
                'last_name' => 'Silva',
                'date_of_birth' => '1975-09-30',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Accountant',
                'workplace' => 'Silva & Associates',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '654 Ward Place',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0501',
                'mobile_phone' => '+94-77-555-0502',
                'work_phone' => '+94-11-555-0503',
                'email' => 'chamara.silva@email.com',
            ],
            [
                'first_name' => 'Nethmi',
                'middle_name' => 'Thilini',
                'last_name' => 'Dissanayake',
                'date_of_birth' => '1981-12-03',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Marketing Manager',
                'workplace' => 'Colombo Marketing Solutions',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => false,
                'address_line1' => '987 Bauddhaloka Mawatha',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00400',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0601',
                'mobile_phone' => '+94-77-555-0602',
                'email' => 'nethmi.dissanayake@email.com',
            ],
            [
                'first_name' => 'Dineth',
                'middle_name' => 'Jayantha',
                'last_name' => 'Jayawardena',
                'date_of_birth' => '1979-04-18',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Police Officer',
                'workplace' => 'Sri Lanka Police',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '147 Elvitigala Mawatha',
                'address_line2' => 'House 5',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00500',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0701',
                'mobile_phone' => '+94-77-555-0702',
                'work_phone' => '+94-11-555-0703',
                'email' => 'dineth.jayawardena@email.com',
            ],
            [
                'first_name' => 'Sanduni',
                'middle_name' => 'Vindya',
                'last_name' => 'Bandara',
                'date_of_birth' => '1984-08-25',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Graphic Designer',
                'workplace' => 'Creative Lanka',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '258 Kynsey Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00800',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0801',
                'mobile_phone' => '+94-77-555-0802',
                'email' => 'sanduni.bandara@email.com',
            ],
            [
                'first_name' => 'Kavinda',
                'middle_name' => 'Ashan',
                'last_name' => 'Wickramasinghe',
                'date_of_birth' => '1977-01-12',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Construction Manager',
                'workplace' => 'Lanka Builders',
                'relationship_type' => 'Father',
                'is_emergency_contact' => false,
                'address_line1' => '369 Gregory Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-0901',
                'mobile_phone' => '+94-77-555-0902',
                'work_phone' => '+94-11-555-0903',
                'email' => 'kavinda.wickramasinghe@email.com',
            ],
            [
                'first_name' => 'Thisuri',
                'middle_name' => 'Nimasha',
                'last_name' => 'Gunasekara',
                'date_of_birth' => '1985-06-07',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Pharmacist',
                'workplace' => 'State Pharmaceuticals',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '741 Deans Road',
                'address_line2' => 'Building A',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-1001',
                'mobile_phone' => '+94-77-555-1002',
                'email' => 'thisuri.gunasekara@email.com',
            ],
        ];

        foreach ($parents as $parentData) {
            // Create user account for parent
            $user = User::create([
                'name' => $parentData['first_name'] . ' ' . $parentData['last_name'],
                'email' => $parentData['email'],
                'password' => Hash::make('password123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign parent role
            $user->assignRole('Parent');

            // Create parent record
            $parent = ParentModel::create([
                'user_id' => $user->id,
                'parent_code' => ParentModel::generateParentCode(),
                'first_name' => $parentData['first_name'],
                'middle_name' => $parentData['middle_name'],
                'last_name' => $parentData['last_name'],
                'date_of_birth' => $parentData['date_of_birth'],
                'gender' => $parentData['gender'],
                'nationality' => $parentData['nationality'],
                'occupation' => $parentData['occupation'],
                'workplace' => $parentData['workplace'],
                'relationship_type' => $parentData['relationship_type'],
                'is_emergency_contact' => $parentData['is_emergency_contact'],
                'is_active' => true,
                'address_line1' => $parentData['address_line1'],
                'address_line2' => $parentData['address_line2'] ?? null,
                'city' => $parentData['city'],
                'state' => $parentData['state'],
                'postal_code' => $parentData['postal_code'],
                'country' => $parentData['country'],
                'home_phone' => $parentData['home_phone'],
                'mobile_phone' => $parentData['mobile_phone'],
                'work_phone' => $parentData['work_phone'] ?? null,
                'email' => $parentData['email'],
            ]);

            $this->command->info("Created parent: {$parent->full_name} ({$parent->parent_code})");
        }
    }
}
