<?php

namespace Database\Seeders;

use App\Models\SecurityStaff;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class SecurityStaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $securityStaff = [
            [
                'first_name' => 'Tharusha',
                'middle_name' => 'Lakshitha',
                'last_name' => 'Rashmika',
                'date_of_birth' => '1985-04-12',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-01-15',
                'employee_id' => 'EMP-SEC-001',
                'shift' => 'Morning',
                'position' => 'Security Supervisor',
                'address_line1' => '123 Galle Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2101',
                'mobile_phone' => '+94-77-555-2102',
                'email' => 'tharusha.rashmika@school.edu',
            ],
            [
                'first_name' => 'Dilmi',
                'middle_name' => 'Sachini',
                'last_name' => 'Samaranayaka',
                'date_of_birth' => '1988-08-22',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-02-01',
                'employee_id' => 'EMP-SEC-002',
                'shift' => 'Evening',
                'position' => 'Security Guard',
                'address_line1' => '456 Duplication Road',
                'address_line2' => 'Apartment 3B',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00400',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2201',
                'mobile_phone' => '+94-77-555-2202',
                'email' => 'dilmi.samaranayaka@school.edu',
            ],
            [
                'first_name' => 'Susiru',
                'middle_name' => 'Prasanna',
                'last_name' => 'Wijesiri',
                'date_of_birth' => '1982-11-30',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-03-10',
                'employee_id' => 'EMP-SEC-003',
                'shift' => 'Night',
                'position' => 'Security Guard',
                'address_line1' => '789 Flower Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2301',
                'mobile_phone' => '+94-77-555-2302',
                'email' => 'susiru.wijesiri@school.edu',
            ],
            [
                'first_name' => 'Oushadee',
                'middle_name' => 'Vindya',
                'last_name' => 'Perera',
                'date_of_birth' => '1990-01-18',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-04-05',
                'employee_id' => 'EMP-SEC-004',
                'shift' => 'Morning',
                'position' => 'Security Guard',
                'address_line1' => '321 Baseline Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00900',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2401',
                'mobile_phone' => '+94-77-555-2402',
                'email' => 'oushadee.perera@school.edu',
            ],
            [
                'first_name' => 'Kavinda',
                'middle_name' => 'Jayantha',
                'last_name' => 'Fernando',
                'date_of_birth' => '1987-06-14',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-05-20',
                'employee_id' => 'EMP-SEC-005',
                'shift' => 'Evening',
                'position' => 'Security Guard',
                'address_line1' => '654 Havelock Road',
                'address_line2' => 'Unit 12',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00500',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2501',
                'mobile_phone' => '+94-77-555-2502',
                'email' => 'kavinda.fernando@school.edu',
            ],
            [
                'first_name' => 'Nethmi',
                'middle_name' => 'Thilini',
                'last_name' => 'Silva',
                'date_of_birth' => '1984-09-07',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-06-12',
                'employee_id' => 'EMP-SEC-006',
                'shift' => 'Night',
                'position' => 'Security Guard',
                'address_line1' => '987 Ward Place',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2601',
                'mobile_phone' => '+94-77-555-2602',
                'email' => 'nethmi.silva@school.edu',
            ],
            [
                'first_name' => 'Nisal',
                'middle_name' => 'Chamara',
                'last_name' => 'Dissanayake',
                'date_of_birth' => '1986-12-25',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-07-08',
                'employee_id' => 'EMP-SEC-007',
                'shift' => 'Morning',
                'position' => 'Security Officer',
                'address_line1' => '147 Maradana Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2701',
                'mobile_phone' => '+94-77-555-2702',
                'email' => 'nisal.dissanayake@school.edu',
            ],
            [
                'first_name' => 'Sanduni',
                'middle_name' => 'Madhushika',
                'last_name' => 'Jayawardena',
                'date_of_birth' => '1989-03-16',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-08-15',
                'employee_id' => 'EMP-SEC-008',
                'shift' => 'Evening',
                'position' => 'Security Officer',
                'address_line1' => '258 Elvitigala Mawatha',
                'address_line2' => 'Building C',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00500',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2801',
                'mobile_phone' => '+94-77-555-2802',
                'email' => 'sanduni.jayawardena@school.edu',
            ],
            [
                'first_name' => 'Chamod',
                'middle_name' => 'Ashan',
                'last_name' => 'Bandara',
                'date_of_birth' => '1983-07-09',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-09-03',
                'employee_id' => 'EMP-SEC-009',
                'shift' => 'Night',
                'position' => 'Security Officer',
                'address_line1' => '369 Bauddhaloka Mawatha',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00400',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-2901',
                'mobile_phone' => '+94-77-555-2902',
                'email' => 'chamod.bandara@school.edu',
            ],
            [
                'first_name' => 'Thisuri',
                'middle_name' => 'Nimasha',
                'last_name' => 'Wickramasinghe',
                'date_of_birth' => '1991-10-28',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'joining_date' => '2023-10-12',
                'employee_id' => 'EMP-SEC-010',
                'shift' => 'Morning',
                'position' => 'Security Guard',
                'address_line1' => '741 Kynsey Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00800',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3001',
                'mobile_phone' => '+94-77-555-3002',
                'email' => 'thisuri.wickramasinghe@school.edu',
            ],
        ];

        foreach ($securityStaff as $index => $staffData) {
            // Create user account for security staff
            $user = User::create([
                'name' => $staffData['first_name'] . ' ' . $staffData['last_name'],
                'email' => $staffData['email'],
                'password' => Hash::make('security123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign security role
            $user->assignRole('Security');

            // Generate unique security code for seeding
            $year = substr($staffData['joining_date'], 0, 4); // Extract year from joining_date
            $securityCode = 'SEC' . $year . str_pad($index + 1, 4, '0', STR_PAD_LEFT);

            // Create security staff record
            $security = SecurityStaff::create([
                'user_id' => $user->id,
                'security_code' => $securityCode,
                'first_name' => $staffData['first_name'],
                'middle_name' => $staffData['middle_name'],
                'last_name' => $staffData['last_name'],
                'date_of_birth' => $staffData['date_of_birth'],
                'gender' => $staffData['gender'],
                'nationality' => $staffData['nationality'],
                'joining_date' => $staffData['joining_date'],
                'employee_id' => $staffData['employee_id'],
                'shift' => $staffData['shift'],
                'position' => $staffData['position'],
                'is_active' => true,
                'address_line1' => $staffData['address_line1'],
                'address_line2' => $staffData['address_line2'] ?? null,
                'city' => $staffData['city'],
                'state' => $staffData['state'],
                'postal_code' => $staffData['postal_code'],
                'country' => $staffData['country'],
                'home_phone' => $staffData['home_phone'],
                'mobile_phone' => $staffData['mobile_phone'],
                'email' => $staffData['email'],
            ]);

            $this->command->info("Created security staff: {$security->full_name} ({$security->security_code})");
        }
    }
}
