<?php

namespace Database\Seeders;

use App\Models\Subject;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'first_name' => 'Hansika',
                'middle_name' => 'Madhushika',
                'last_name' => 'Rashmika',
                'date_of_birth' => '1985-09-15',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Education, Master of Arts in Mathematics',
                'specialization' => 'Mathematics',
                'experience_years' => 8.5,
                'joining_date' => '2022-08-15',
                'employee_id' => 'EMP-TEA-001',
                'teaching_level' => 'Primary',
                'address_line1' => '123 Galle Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3101',
                'mobile_phone' => '+94-77-555-3102',
                'email' => 'hansika.rashmika@school.edu',
                'subjects' => ['Mathematics'],
            ],
            [
                'first_name' => 'Nisal',
                'middle_name' => 'Lakshitha',
                'last_name' => 'Samaranayaka',
                'date_of_birth' => '1982-04-22',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Arts in English, Master of Education',
                'specialization' => 'English Language Arts',
                'experience_years' => 12.0,
                'joining_date' => '2021-08-20',
                'employee_id' => 'EMP-TEA-002',
                'teaching_level' => 'Primary',
                'address_line1' => '456 Baseline Road',
                'address_line2' => 'Apartment 5C',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00600',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3201',
                'mobile_phone' => '+94-77-555-3202',
                'email' => 'nisal.samaranayaka@school.edu',
                'subjects' => ['English Language Arts', 'Library Skills'],
            ],
            [
                'first_name' => 'Madushani',
                'middle_name' => 'Vindya',
                'last_name' => 'Wijesiri',
                'date_of_birth' => '1988-12-08',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Science in Biology, Teaching Certificate',
                'specialization' => 'Science',
                'experience_years' => 6.0,
                'joining_date' => '2023-01-10',
                'employee_id' => 'EMP-TEA-003',
                'teaching_level' => 'Secondary',
                'address_line1' => '789 Horton Place',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3301',
                'mobile_phone' => '+94-77-555-3302',
                'email' => 'madushani.wijesiri@school.edu',
                'subjects' => ['Science'],
            ],
            [
                'first_name' => 'Lahiru',
                'middle_name' => 'Prasanna',
                'last_name' => 'Perera',
                'date_of_birth' => '1980-07-14',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Arts in History, Master of Education',
                'specialization' => 'Social Studies',
                'experience_years' => 15.5,
                'joining_date' => '2020-08-25',
                'employee_id' => 'EMP-TEA-004',
                'teaching_level' => 'Secondary',
                'address_line1' => '321 Flower Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3401',
                'mobile_phone' => '+94-77-555-3402',
                'email' => 'lahiru.perera@school.edu',
                'subjects' => ['Social Studies'],
            ],
            [
                'first_name' => 'Ishara',
                'middle_name' => 'Sachini',
                'last_name' => 'Fernando',
                'date_of_birth' => '1987-03-28',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Fine Arts, Teaching Certificate',
                'specialization' => 'Visual Arts',
                'experience_years' => 7.5,
                'joining_date' => '2022-09-05',
                'employee_id' => 'EMP-TEA-005',
                'teaching_level' => 'Primary',
                'address_line1' => '654 Baudhaloka Mawatha',
                'address_line2' => 'Studio 2B',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00400',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3501',
                'mobile_phone' => '+94-77-555-3502',
                'email' => 'ishara.fernando@school.edu',
                'subjects' => ['Visual Arts'],
            ],
            [
                'first_name' => 'Chamod',
                'middle_name' => 'Jayantha',
                'last_name' => 'Silva',
                'date_of_birth' => '1984-11-12',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Music Education, Master of Arts in Music',
                'specialization' => 'Music',
                'experience_years' => 9.0,
                'joining_date' => '2021-08-30',
                'employee_id' => 'EMP-TEA-006',
                'teaching_level' => 'Primary',
                'address_line1' => '987 Reid Avenue',
                'city' => 'Colombo',
                'state' => 'Illinois',
                'postal_code' => '62706',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3601',
                'mobile_phone' => '+1-217-555-3602',
                'email' => 'david.brown@school.edu',
                'subjects' => ['Music'],
            ],
            [
                'first_name' => 'Piyumi',
                'middle_name' => 'Thilini',
                'last_name' => 'Dissanayake',
                'date_of_birth' => '1986-06-19',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Science in Kinesiology, Teaching Certificate',
                'specialization' => 'Physical Education',
                'experience_years' => 8.0,
                'joining_date' => '2022-07-15',
                'employee_id' => 'EMP-TEA-007',
                'teaching_level' => 'Secondary',
                'address_line1' => '147 Deans Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3701',
                'mobile_phone' => '+94-77-555-3702',
                'email' => 'piyumi.dissanayake@school.edu',
                'subjects' => ['Physical Education'],
            ],
            [
                'first_name' => 'Sahan',
                'middle_name' => 'Chamara',
                'last_name' => 'Jayawardena',
                'date_of_birth' => '1983-02-25',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Arts in Spanish Literature, Teaching Certificate',
                'specialization' => 'Spanish Language',
                'experience_years' => 11.0,
                'joining_date' => '2020-08-12',
                'employee_id' => 'EMP-TEA-008',
                'teaching_level' => 'Secondary',
                'address_line1' => '258 Rosmead Place',
                'address_line2' => 'Building A',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00500',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3801',
                'mobile_phone' => '+94-77-555-3802',
                'email' => 'sahan.jayawardena@school.edu',
                'subjects' => ['Spanish Language'],
            ],
            [
                'first_name' => 'Harshani',
                'middle_name' => 'Nimasha',
                'last_name' => 'Bandara',
                'date_of_birth' => '1989-10-03',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Science in Computer Science, Teaching Certificate',
                'specialization' => 'Technology Education',
                'experience_years' => 5.5,
                'joining_date' => '2023-08-20',
                'employee_id' => 'EMP-TEA-009',
                'teaching_level' => 'A/L-Technology',
                'address_line1' => '369 Dharmapala Mawatha',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-3901',
                'mobile_phone' => '+94-77-555-3902',
                'email' => 'harshani.bandara@school.edu',
                'subjects' => ['Technology Education'],
            ],
            [
                'first_name' => 'Dulaj',
                'middle_name' => 'Ashan',
                'last_name' => 'Wickramasinghe',
                'date_of_birth' => '1981-08-17',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Education, Master of Library Science',
                'specialization' => 'Library Science',
                'experience_years' => 13.0,
                'joining_date' => '2019-08-26',
                'employee_id' => 'EMP-TEA-010',
                'teaching_level' => 'Primary',
                'address_line1' => '741 Wijerama Mawatha',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-555-4001',
                'mobile_phone' => '+94-77-555-4002',
                'email' => 'dulaj.wickramasinghe@school.edu',
                'subjects' => ['Library Skills', 'English Language Arts'],
            ],
        ];

        foreach ($teachers as $teacherData) {
            // Create user account for teacher
            $user = User::create([
                'name' => $teacherData['first_name'] . ' ' . $teacherData['last_name'],
                'email' => $teacherData['email'],
                'password' => Hash::make('teacher123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign teacher role
            $user->assignRole('Teacher');

            // Create teacher record
            $teacher = Teacher::create([
                'user_id' => $user->id,
                'teacher_code' => Teacher::generateTeacherCode(),
                'first_name' => $teacherData['first_name'],
                'middle_name' => $teacherData['middle_name'],
                'last_name' => $teacherData['last_name'],
                'date_of_birth' => $teacherData['date_of_birth'],
                'gender' => $teacherData['gender'],
                'nationality' => $teacherData['nationality'],
                'qualification' => $teacherData['qualification'],
                'specialization' => $teacherData['specialization'],
                'experience_years' => $teacherData['experience_years'],
                'joining_date' => $teacherData['joining_date'],
                'employee_id' => $teacherData['employee_id'],
                'is_active' => true,
                'teaching_level' => $teacherData['teaching_level'],
                'address_line1' => $teacherData['address_line1'],
                'address_line2' => $teacherData['address_line2'] ?? null,
                'city' => $teacherData['city'],
                'state' => $teacherData['state'],
                'postal_code' => $teacherData['postal_code'],
                'country' => $teacherData['country'],
                'home_phone' => $teacherData['home_phone'],
                'mobile_phone' => $teacherData['mobile_phone'],
                'email' => $teacherData['email'],
            ]);

            // Attach subjects to teacher
            foreach ($teacherData['subjects'] as $subjectName) {
                $subject = Subject::where('subject_name', $subjectName)->first();
                if ($subject) {
                    $teacher->subjects()->attach($subject->id);
                }
            }

            $this->command->info("Created teacher: {$teacher->full_name} ({$teacher->teacher_code}) - Subjects: " . implode(', ', $teacherData['subjects']));
        }
    }
}
