<?php

namespace Database\Seeders;

use App\Models\ParentModel;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ParentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parents = [
            [
                'first_name' => 'Chaminda',
                'middle_name' => 'Kumara',
                'last_name' => 'Fernando',
                'date_of_birth' => '1980-03-15',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Software Engineer',
                'workplace' => 'TechCorp Lanka',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '123 Galle Road',
                'address_line2' => 'House 4B',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-234-0101',
                'mobile_phone' => '+94-77-123-0102',
                'work_phone' => '+94-11-234-0103',
                'email' => 'chaminda.fernando@email.lk',
            ],
            [
                'first_name' => 'Priyanthi',
                'middle_name' => 'Kumari',
                'last_name' => 'Silva',
                'date_of_birth' => '1982-07-22',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Teacher',
                'workplace' => 'Colombo International School',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '456 Kandy Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-345-0201',
                'mobile_phone' => '+94-77-234-0202',
                'email' => 'priyanthi.silva@email.lk',
            ],
            [
                'first_name' => 'Ruwan',
                'middle_name' => 'Prabath',
                'last_name' => 'Perera',
                'date_of_birth' => '1978-11-08',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Doctor',
                'workplace' => 'Colombo General Hospital',
                'relationship_type' => 'Father',
                'is_emergency_contact' => false,
                'address_line1' => '789 Negombo Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00500',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-456-0301',
                'mobile_phone' => '+94-77-345-0302',
                'work_phone' => '+94-11-456-0303',
                'email' => 'ruwan.perera@email.lk',
            ],
            [
                'first_name' => 'Anura',
                'middle_name' => 'Priyadarshani',
                'last_name' => 'Jayawardena',
                'date_of_birth' => '1983-05-14',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Nurse',
                'workplace' => 'National Hospital Colombo',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '321 Anuradhapura Road',
                'address_line2' => 'Unit 12',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-567-0401',
                'mobile_phone' => '+94-77-456-0402',
                'email' => 'anura.jayawardena@email.lk',
            ],
            [
                'first_name' => 'Saman',
                'middle_name' => 'Kumara',
                'last_name' => 'Bandara',
                'date_of_birth' => '1975-09-30',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Accountant',
                'workplace' => 'Bandara & Associates',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '654 Colombo Road',
                'city' => 'Kandy',
                'state' => 'Central Province',
                'postal_code' => '20000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-81-234-0501',
                'mobile_phone' => '+94-77-567-0502',
                'work_phone' => '+94-81-234-0503',
                'email' => 'saman.bandara@email.lk',
            ],
            [
                'first_name' => 'Nilmini',
                'middle_name' => 'Kumudini',
                'last_name' => 'Rajapaksa',
                'date_of_birth' => '1981-12-03',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Marketing Manager',
                'workplace' => 'Rajapaksa Marketing Group',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => false,
                'address_line1' => '987 Temple Road',
                'city' => 'Kandy',
                'state' => 'Central Province',
                'postal_code' => '20000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-81-345-0601',
                'mobile_phone' => '+94-77-678-0602',
                'email' => 'nilmini.rajapaksa@email.lk',
            ],
            [
                'first_name' => 'Tharindu',
                'middle_name' => 'Prabath',
                'last_name' => 'Weerasinghe',
                'date_of_birth' => '1979-04-18',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Police Officer',
                'workplace' => 'Sri Lanka Police Department',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '147 Galle Road',
                'address_line2' => 'House 5',
                'city' => 'Galle',
                'state' => 'Southern Province',
                'postal_code' => '80000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-91-234-0701',
                'mobile_phone' => '+94-77-789-0702',
                'work_phone' => '+94-91-234-0703',
                'email' => 'tharindu.weerasinghe@email.lk',
            ],
            [
                'first_name' => 'Deepika',
                'middle_name' => 'Priyanthi',
                'last_name' => 'Wickramasinghe',
                'date_of_birth' => '1984-08-25',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Graphic Designer',
                'workplace' => 'Creative Solutions Lanka',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '258 Jaffna Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-890-0801',
                'mobile_phone' => '+94-77-890-0802',
                'email' => 'deepika.wickramasinghe@email.lk',
            ],
            [
                'first_name' => 'Mohamed',
                'middle_name' => 'Fazal',
                'last_name' => 'Hussain',
                'date_of_birth' => '1977-01-12',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Construction Manager',
                'workplace' => 'Hussain Construction',
                'relationship_type' => 'Father',
                'is_emergency_contact' => false,
                'address_line1' => '369 Nuwara Eliya Road',
                'city' => 'Kandy',
                'state' => 'Central Province',
                'postal_code' => '22200',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-81-456-0901',
                'mobile_phone' => '+94-77-901-0902',
                'work_phone' => '+94-81-456-0903',
                'email' => 'mohamed.hussain@email.lk',
            ],
            [
                'first_name' => 'Chamari',
                'middle_name' => 'Kumudini',
                'last_name' => 'Gunawardena',
                'date_of_birth' => '1985-06-07',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'occupation' => 'Pharmacist',
                'workplace' => 'Colombo Pharmacy',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '741 Matara Road',
                'address_line2' => 'Building A',
                'city' => 'Galle',
                'state' => 'Southern Province',
                'postal_code' => '80000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-91-345-1001',
                'mobile_phone' => '+94-77-012-1002',
                'email' => 'chamari.gunawardena@email.lk',
            ],
        ];

        foreach ($parents as $parentData) {
            // Create user account for parent
            $user = User::create([
                'name' => $parentData['first_name'].' '.$parentData['last_name'],
                'email' => $parentData['email'],
                'password' => Hash::make('password123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign parent role
            $user->assignRole('Parent');

            // Create parent record
            $parent = ParentModel::create([
                'user_id' => $user->id,
                'parent_code' => ParentModel::generateParentCode(),
                'first_name' => $parentData['first_name'],
                'middle_name' => $parentData['middle_name'],
                'last_name' => $parentData['last_name'],
                'date_of_birth' => $parentData['date_of_birth'],
                'gender' => $parentData['gender'],
                'nationality' => $parentData['nationality'],
                'occupation' => $parentData['occupation'],
                'workplace' => $parentData['workplace'],
                'relationship_type' => $parentData['relationship_type'],
                'is_emergency_contact' => $parentData['is_emergency_contact'],
                'is_active' => true,
                'address_line1' => $parentData['address_line1'],
                'address_line2' => $parentData['address_line2'] ?? null,
                'city' => $parentData['city'],
                'state' => $parentData['state'],
                'postal_code' => $parentData['postal_code'],
                'country' => $parentData['country'],
                'home_phone' => $parentData['home_phone'],
                'mobile_phone' => $parentData['mobile_phone'],
                'work_phone' => $parentData['work_phone'] ?? null,
                'email' => $parentData['email'],
            ]);

            $this->command->info("Created parent: {$parent->full_name} ({$parent->parent_code})");
        }
    }
}
