<?php

namespace Database\Seeders;

use App\Models\Subject;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'first_name' => 'Nimal',
                'middle_name' => 'Kumara',
                'last_name' => 'Fernando',
                'date_of_birth' => '1985-09-15',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Education, Master of Arts in Elementary Education',
                'specialization' => 'Mathematics',
                'experience_years' => 8.5,
                'joining_date' => '2022-08-15',
                'employee_id' => 'EMP-TEA-001',
                'teaching_level' => 'Primary',
                'address_line1' => '123 Galle Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-2345678',
                'mobile_phone' => '+94-77-1234567',
                'email' => 'nimal.fernando@school.lk',
                'subjects' => ['Mathematics'],
            ],
            [
                'first_name' => 'Kumari',
                'middle_name' => 'Priyanthi',
                'last_name' => 'Silva',
                'date_of_birth' => '1982-04-22',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Arts in English, Master of Education',
                'specialization' => 'English Language Arts',
                'experience_years' => 12.0,
                'joining_date' => '2021-08-20',
                'employee_id' => 'EMP-TEA-002',
                'teaching_level' => 'Primary',
                'address_line1' => '456 Kandy Road',
                'address_line2' => 'Apt 5C',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-3456789',
                'mobile_phone' => '+94-77-2345678',
                'email' => 'kumari.silva@school.lk',
                'subjects' => ['English Language Arts', 'Library Skills'],
            ],
            [
                'first_name' => 'Ruwan',
                'middle_name' => 'Chaminda',
                'last_name' => 'Perera',
                'date_of_birth' => '1988-12-08',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Science in Biology, Teaching Certificate',
                'specialization' => 'Science',
                'experience_years' => 6.0,
                'joining_date' => '2023-01-10',
                'employee_id' => 'EMP-TEA-003',
                'teaching_level' => 'Secondary',
                'address_line1' => '789 Negombo Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00500',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-4567890',
                'mobile_phone' => '+94-77-3456789',
                'email' => 'ruwan.perera@school.lk',
                'subjects' => ['Science'],
            ],
            [
                'first_name' => 'Anura',
                'middle_name' => 'Priyanka',
                'last_name' => 'Jayawardena',
                'date_of_birth' => '1980-07-14',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Arts in History, Master of Education',
                'specialization' => 'Social Studies',
                'experience_years' => 15.5,
                'joining_date' => '2020-08-25',
                'employee_id' => 'EMP-TEA-004',
                'teaching_level' => 'Secondary',
                'address_line1' => '321 Anuradhapura Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-5678901',
                'mobile_phone' => '+94-77-4567890',
                'email' => 'anura.jayawardena@school.lk',
                'subjects' => ['Social Studies'],
            ],
            [
                'first_name' => 'Chamari',
                'middle_name' => 'Kumudini',
                'last_name' => 'Gunawardena',
                'date_of_birth' => '1987-03-28',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Fine Arts, Teaching Certificate',
                'specialization' => 'Visual Arts',
                'experience_years' => 7.5,
                'joining_date' => '2022-09-05',
                'employee_id' => 'EMP-TEA-005',
                'teaching_level' => 'Primary',
                'address_line1' => '654 Colombo Road',
                'address_line2' => 'Studio 2B',
                'city' => 'Kandy',
                'state' => 'Central Province',
                'postal_code' => '20000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-81-2345678',
                'mobile_phone' => '+94-77-5678901',
                'email' => 'chamari.gunawardena@school.lk',
                'subjects' => ['Visual Arts'],
            ],
            [
                'first_name' => 'Saman',
                'middle_name' => 'Kumara',
                'last_name' => 'Bandara',
                'date_of_birth' => '1984-11-12',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Music Education, Master of Arts in Music',
                'specialization' => 'Music',
                'experience_years' => 9.0,
                'joining_date' => '2021-08-30',
                'employee_id' => 'EMP-TEA-006',
                'teaching_level' => 'Primary',
                'address_line1' => '987 Temple Road',
                'city' => 'Kandy',
                'state' => 'Central Province',
                'postal_code' => '20000',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-81-3456789',
                'mobile_phone' => '+94-77-6789012',
                'email' => 'saman.bandara@school.lk',
                'subjects' => ['Music'],
            ],
            [
                'first_name' => 'Nilmini',
                'middle_name' => 'Kumari',
                'last_name' => 'Rajapaksa',
                'date_of_birth' => '1986-06-19',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Science in Kinesiology, Teaching Certificate',
                'specialization' => 'Physical Education',
                'experience_years' => 8.0,
                'joining_date' => '2022-07-15',
                'employee_id' => 'EMP-TEA-007',
                'teaching_level' => 'Secondary',
                'address_line1' => '147 Stadium Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-6789012',
                'mobile_phone' => '+94-77-7890123',
                'email' => 'nilmini.rajapaksa@school.lk',
                'subjects' => ['Physical Education'],
            ],
            [
                'first_name' => 'Mohamed',
                'middle_name' => 'Fazal',
                'last_name' => 'Hussain',
                'date_of_birth' => '1983-02-25',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Arts in Tamil Literature, Teaching Certificate',
                'specialization' => 'Tamil Language',
                'experience_years' => 11.0,
                'joining_date' => '2020-08-12',
                'employee_id' => 'EMP-TEA-008',
                'teaching_level' => 'Secondary',
                'address_line1' => '258 Jaffna Road',
                'address_line2' => 'Building A',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '01300',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-7890123',
                'mobile_phone' => '+94-77-8901234',
                'email' => 'mohamed.hussain@school.lk',
                'subjects' => ['Tamil Language'],
            ],
            [
                'first_name' => 'Tharindu',
                'middle_name' => 'Prabath',
                'last_name' => 'Weerasinghe',
                'date_of_birth' => '1989-10-03',
                'gender' => 'M',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Science in Computer Science, Teaching Certificate',
                'specialization' => 'Technology Education',
                'experience_years' => 5.5,
                'joining_date' => '2023-08-20',
                'employee_id' => 'EMP-TEA-009',
                'teaching_level' => 'A/L-Technology',
                'address_line1' => '369 Technology Park',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '10250',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-8901234',
                'mobile_phone' => '+94-77-9012345',
                'email' => 'tharindu.weerasinghe@school.lk',
                'subjects' => ['Technology Education'],
            ],
            [
                'first_name' => 'Deepika',
                'middle_name' => 'Priyadarshani',
                'last_name' => 'Wickramasinghe',
                'date_of_birth' => '1981-08-17',
                'gender' => 'F',
                'nationality' => 'Sri Lankan',
                'qualification' => 'Bachelor of Education, Master of Library Science',
                'specialization' => 'Library Science',
                'experience_years' => 13.0,
                'joining_date' => '2019-08-26',
                'employee_id' => 'EMP-TEA-010',
                'teaching_level' => 'Primary',
                'address_line1' => '741 Library Road',
                'city' => 'Colombo',
                'state' => 'Western Province',
                'postal_code' => '00700',
                'country' => 'Sri Lanka',
                'home_phone' => '+94-11-9012345',
                'mobile_phone' => '+94-77-0123456',
                'email' => 'deepika.wickramasinghe@school.lk',
                'subjects' => ['Library Skills', 'English Language Arts'],
            ],
        ];

        foreach ($teachers as $teacherData) {
            // Create user account for teacher
            $user = User::create([
                'name' => $teacherData['first_name'] . ' ' . $teacherData['last_name'],
                'email' => $teacherData['email'],
                'password' => Hash::make('teacher123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign teacher role
            $user->assignRole('Teacher');

            // Create teacher record
            $teacher = Teacher::create([
                'user_id' => $user->id,
                'teacher_code' => Teacher::generateTeacherCode(),
                'first_name' => $teacherData['first_name'],
                'middle_name' => $teacherData['middle_name'],
                'last_name' => $teacherData['last_name'],
                'date_of_birth' => $teacherData['date_of_birth'],
                'gender' => $teacherData['gender'],
                'nationality' => $teacherData['nationality'],
                'qualification' => $teacherData['qualification'],
                'specialization' => $teacherData['specialization'],
                'experience_years' => $teacherData['experience_years'],
                'joining_date' => $teacherData['joining_date'],
                'employee_id' => $teacherData['employee_id'],
                'is_active' => true,
                'address_line1' => $teacherData['address_line1'],
                'address_line2' => $teacherData['address_line2'] ?? null,
                'city' => $teacherData['city'],
                'state' => $teacherData['state'],
                'postal_code' => $teacherData['postal_code'],
                'country' => $teacherData['country'],
                'home_phone' => $teacherData['home_phone'],
                'mobile_phone' => $teacherData['mobile_phone'],
                'email' => $teacherData['email'],
            ]);

            // Attach subjects to teacher
            foreach ($teacherData['subjects'] as $subjectName) {
                $subject = Subject::where('subject_name', $subjectName)->first();
                if ($subject) {
                    $teacher->subjects()->attach($subject->id);
                }
            }

            $this->command->info("Created teacher: {$teacher->full_name} ({$teacher->teacher_code}) - Subjects: " . implode(', ', $teacherData['subjects']));
        }
    }
}
